# Generated by Django 5.1 on 2024-09-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
