# Generated by Django 5.1 on 2024-09-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0002_services_service_icon_services_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='keysevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='topbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('phoneno', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=200)),
            ],
        ),
    ]
