# Generated by Django 5.1 on 2024-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0003_keysevices_topbar_welcome_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
