# Generated by Django 5.1 on 2024-09-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0004_alter_topbar_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keysevices',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='welcome',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='why',
            old_name='Desc',
            new_name='desc',
        ),
    ]
