# Generated by Django 5.1 on 2024-09-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0005_rename_desc_keysevices_desc_rename_desc_welcome_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keysevices',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='why',
            name='desc',
        ),
    ]
