# Generated by Django 5.1 on 2024-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0006_remove_keysevices_desc_remove_welcome_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keysevices',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='welcome',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='why',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
    ]
