# Generated by Django 5.1 on 2024-09-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0007_keysevices_desc_welcome_desc_why_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keysevices',
            new_name='keyservices',
        ),
    ]
