# Generated by Django 5.1 on 2024-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0008_rename_keysevices_keyservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='page_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
