# Generated by Django 5.1 on 2024-09-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0009_title_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoLink', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsKeyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kservice_icon', models.CharField(max_length=100, null=True)),
                ('kservice_title', models.CharField(max_length=200, null=True)),
                ('kservice_desc', models.TextField()),
            ],
        ),
    ]
