# Generated by Django 5.1 on 2024-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0011_rename_aboutuskeyservices_aboutusstatitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsVideoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoLink', models.CharField(max_length=200)),
                ('videoimg', models.ImageField(upload_to='about_us')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
