# Generated by Django 5.1 on 2024-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0012_aboutusdesc_aboutusvideoimage_delete_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='heroimg',
            field=models.ImageField(null=True, upload_to='welcome'),
        ),
    ]
