# Generated by Django 5.1 on 2024-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0013_welcome_heroimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUsStatitems',
            new_name='AboutUskservices',
        ),
        migrations.RenameField(
            model_name='aboutuskservices',
            old_name='statitems_desc',
            new_name='kservice_desc',
        ),
        migrations.RenameField(
            model_name='aboutuskservices',
            old_name='statitems_icon',
            new_name='kservice_icon',
        ),
        migrations.RenameField(
            model_name='aboutuskservices',
            old_name='statitems_title',
            new_name='kservice_title',
        ),
    ]
