# Generated by Django 5.1 on 2024-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0014_rename_aboutusstatitems_aboutuskservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='statitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_icon', models.CharField(max_length=100)),
                ('stat_counter', models.CharField(max_length=100)),
                ('stat_label', models.CharField(max_length=100)),
            ],
        ),
    ]
