# Generated by Django 5.1 on 2024-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0017_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='img',
            field=models.ImageField(default='', upload_to='department'),
        ),
    ]
