# Generated by Django 5.1 on 2024-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0020_doctor_xlink_doctor_fbooklink_doctor_instalink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=100)),
                ('ans', models.TextField()),
            ],
        ),
    ]
