# Generated by Django 5.1 on 2024-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0023_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNo', models.CharField(max_length=100)),
            ],
        ),
    ]
