# Generated by Django 5.1 on 2024-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0024_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='XLink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='fbookLink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='instaLink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='linkedInLink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
