# Generated by Django 5.1 on 2024-09-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0025_address_xlink_address_fbooklink_address_instalink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUskservices',
            new_name='AboutUskservice',
        ),
        migrations.RenameModel(
            old_name='departments',
            new_name='department',
        ),
        migrations.RenameModel(
            old_name='keyservices',
            new_name='keyservice',
        ),
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
        migrations.RenameModel(
            old_name='statitems',
            new_name='statitem',
        ),
    ]
