# Generated by Django 5.1 on 2024-09-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0026_rename_aboutuskservices_aboutuskservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='logo_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
